const KEY="bookCreationStudio.v01";
const tabs=["Overview","Manuscript","Illustrations","Production","Publishing","Project Log"];
const workflows={"Children's Picture Book":{"Manuscript":["Define concept and audience","Develop story outline","Draft manuscript","Review and revise manuscript","Lock manuscript","Break manuscript into pages / spreads"],"Illustrations":["Approve Character Master","Approve Environment Master","Approve Style Master","Create Illustration Schedule","Generate / source scene images","Review scene sequence","Approve final illustrations"],"Production":["Confirm trim size, bleed and margins","Set up Affinity document","Place final text and images","Preflight image resolution and layout","Export print-ready interior PDF","Create and check cover"],"Publishing":["Prepare title, subtitle and description","Prepare keywords and categories","Set pricing and territories","Upload manuscript and cover to KDP","Run KDP preview","Order / review proof","Publish","Prepare A+ Content"]},"Illustrated Non-Fiction":{"Manuscript":["Define concept and reader","Create chapter structure","Research and draft entries","Fact-check sources and claims","Edit and proofread","Lock manuscript"],"Illustrations":["Define illustration style","Create illustration list","Produce / source artwork","Review and approve artwork"],"Production":["Confirm trim and interior specification","Build Affinity document","Place text and artwork","Preflight","Export print-ready PDF","Create cover"],"Publishing":["Prepare KDP metadata","Keywords and categories","Pricing","Upload and preview","Proof","Publish","A+ Content"]}};
const generic={"Manuscript":["Define concept and audience","Create structure","Draft content","Review and edit","Proofread","Lock manuscript"],"Illustrations":["Decide whether artwork is required","Create artwork list","Produce / source artwork","Approve final artwork"],"Production":["Confirm book specification","Compile interior","Preflight","Export final files","Create cover"],"Publishing":["Prepare metadata","Keywords and categories","Pricing","Upload and preview","Proof","Publish"]};
let data=JSON.parse(localStorage.getItem(KEY)||'{"books":[]}'),current=null,active="Overview";
const $=s=>document.querySelector(s);
function ensureBook(b){
if(!b.spreads)b.spreads=[];
if(!b.log)b.log=[];
if(!b.story)b.story={premise:"",audience:"5–7",wordTarget:"",tone:"Gentle, cosy and reassuring",manuscript:"",notes:"",status:"Idea"};
if(!b.structure)b.structure={pageCount:24,frontPages:3,endPages:1,mode:"spreads"};
if(!b.pagePlanProposal)b.pagePlanProposal=[];
if(!b.illustration)b.illustration={styleMaster:{name:"",description:"",notes:"",status:"Not Started"},characters:[],environments:[]};
b.spreads.forEach(s=>{if(!s.illustrationStatus)s.illustrationStatus="Not Started";if(!s.imageNotes)s.imageNotes="";if(!s.imageRef)s.imageRef=""});
return b}
data.books.forEach(ensureBook);
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function makeWorkflow(type){let src=workflows[type]||generic,o={};for(const [stage,items] of Object.entries(src))o[stage]=items.map(name=>({name,status:"Not Started"}));return o}
function pct(b){let a=Object.values(b.workflow).flat(),n=a.filter(x=>x.status==="Complete").length;return a.length?Math.round(n/a.length*100):0}
function renderBooks(){let box=$("#books");if(!data.books.length){box.innerHTML='<div class="panel empty"><h3>No book projects yet</h3><p class="muted">Create your first project to generate its workflow.</p><button class="primary" onclick="openNew()">Create First Book</button></div>';return}box.innerHTML=data.books.map(b=>`<article class="card" onclick="openBook('${b.id}')"><span class="badge">${esc(b.type)}</span><h3>${esc(b.title)}</h3><p class="muted">${esc(b.series||"Standalone")} · ${esc(b.formats)}</p><div class="progress"><span style="width:${pct(b)}%"></span></div><strong>${pct(b)}% complete</strong><p class="small muted">${b.spreads.length} page/spread records · Story: ${esc(b.story.status)}</p></article>`).join("")}
function openNew(){$("#bookDialog").showModal()}
function openBook(id){current=ensureBook(data.books.find(b=>b.id===id));active="Overview";$("#dashboard").classList.add("hidden");$("#workspace").classList.remove("hidden");renderWorkspace()}
function renderWorkspace(){let b=current;$("#bookHeader").innerHTML=`<h2>${esc(b.title)}</h2><p class="muted">${esc(b.type)} · ${esc(b.author)} · ${esc(b.imprint)}</p>`;$("#tabs").innerHTML=tabs.map(t=>`<button class="${t===active?"active":""}" onclick="showTab('${t}')">${t}</button>`).join("");renderTab()}
function showTab(t){active=t;renderWorkspace()}
function renderTab(){let b=current,c=$("#tabContent");
if(active==="Overview"){c.innerHTML=`<div class="grid"><div class="panel"><h3>Project</h3><p><b>Series:</b> ${esc(b.series||"—")}</p><p><b>Trim:</b> ${esc(b.trim||"—")}</p><p><b>Interior:</b> ${esc(b.interior)}</p><p><b>Formats:</b> ${esc(b.formats)}</p></div><div class="panel"><h3>Progress</h3><div class="progress"><span style="width:${pct(b)}%"></span></div><h2>${pct(b)}%</h2><p class="muted">Based on completed workflow tasks.</p></div></div><div class="note"><b>Creation flow:</b> develop the story → approve manuscript → create page plan → prepare illustration briefs → generate/review artwork → production and publishing.</div>`;return}
if(active==="Manuscript"){renderManuscript(c,b);return}
if(active==="Illustrations"){renderIllustrations(c,b);return}
if(active==="Project Log"){c.innerHTML=`<div class="panel"><h3>Project Log</h3>${b.log.map(x=>`<p><b>${x.date}</b> — ${esc(x.text)}</p>`).join("")||"<p class=muted>No entries yet.</p>"}<form onsubmit="addLog(event)"><input id="logText" placeholder="Add a decision, change or milestone…" required><button class="primary">Add Entry</button></form></div>`;return}
let tasks=b.workflow[active]||[];c.innerHTML=`<div class="panel"><h3>${active}</h3>${tasks.map((x,i)=>`<div class="task"><span>${esc(x.name)}</span><select onchange="setStatus('${active}',${i},this.value)">${["Not Started","In Progress","Review","Complete"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></div>`).join("")}</div>`}
function renderManuscript(c,b){let st=b.story,sc=b.structure||{pageCount:24,frontPages:3,endPages:1,mode:"spreads"};c.innerHTML=`<div class="manuscript-head"><div><h3>Story Workspace</h3><p class="muted">Develop and approve the whole story before breaking it into the book's page structure.</p></div><button class="primary" onclick="saveStory()">Save Story</button></div>
<div class="ai-panel"><div class="ai-head"><div><h3>Generation Engine</h3><p class="muted">Optional AI assistance. The book remains fully editable and usable without this service.</p></div><span class="ai-status ${aiConfigured()?"ai-ok":"ai-off"}">${aiConfigured()?"Service configured":"Not configured"}</span></div><div class="settings-grid"><label>Secure generation service URL<input id="aiEndpoint" value="${attr(getAISettings().endpoint)}" placeholder="e.g. https://your-service.example.com"></label><button class="secondary" onclick="saveAISettings()">Save Connection</button></div><div class="ai-actions"><button class="secondary" onclick="runTextAI('developIdea')">Develop Idea</button><button class="secondary" onclick="runTextAI('generateDraft')">Generate Story Draft</button><button class="secondary" onclick="runTextAI('reviseStory')">Improve / Revise Story</button><button class="primary" onclick="runTextAI('pagePlan')">Create Intelligent Page Plan</button></div><div id="aiResult"></div></div>
<div class="stagebar">${["Idea","Outline","Draft","Review","Approved"].map(x=>`<span class="stagepill ${x===st.status?"on":""}">${x}</span>`).join("")}</div>
<div class="story-grid"><div class="panel story-editor"><label>Working / final manuscript<textarea id="storyManuscript" placeholder="Write or paste the complete story here…">${esc(st.manuscript)}</textarea></label><label>Story notes<textarea id="storyNotes">${esc(st.notes)}</textarea></label></div>
<div class="panel"><h3>Story Brief</h3><label>Premise / idea<textarea id="storyPremise">${esc(st.premise)}</textarea></label><label>Target audience<input id="storyAudience" value="${esc(st.audience)}"></label><label>Target word count<input id="storyWords" value="${esc(st.wordTarget)}" placeholder="e.g. 650"></label><label>Tone / style<textarea id="storyTone">${esc(st.tone)}</textarea></label><label>Development status<select id="storyStatus">${["Idea","Outline","Draft","Review","Approved"].map(x=>`<option ${x===st.status?"selected":""}>${x}</option>`).join("")}</select></label></div></div>

<div class="manuscript-head"><div><h3>Book Structure Setup</h3><p class="muted">Choose the physical page structure before creating the story page plan.</p></div></div>
<div class="panel"><div class="structure-setup">
<label>Total pages<select id="cfgPages">${[24,28,32].map(x=>`<option ${x===Number(sc.pageCount)?"selected":""}>${x}</option>`).join("")}<option value="custom" ${![24,28,32].includes(Number(sc.pageCount))?"selected":""}>Custom</option></select></label>
<label>Custom pages<input id="cfgCustom" type="number" min="8" step="2" value="${![24,28,32].includes(Number(sc.pageCount))?Number(sc.pageCount):""}" placeholder="e.g. 36"></label>
<label>Front matter pages<input id="cfgFront" type="number" min="0" value="${Number(sc.frontPages)}"></label>
<label>End matter pages<input id="cfgEnd" type="number" min="0" value="${Number(sc.endPages)}"></label>
<label class="wide">Story layout<select id="cfgMode"><option value="spreads" ${sc.mode==="spreads"?"selected":""}>Mostly two-page story spreads</option><option value="pages" ${sc.mode==="pages"?"selected":""}>Individual story pages</option></select></label>
<div class="wide"><button class="secondary" onclick="saveStructure()">Save Structure Setup</button> <button class="primary" onclick="createPagePlan()">Create Page Plan</button></div>
</div><div class="plan-summary">${structureSummary(b)}</div></div>

${renderProposal(b)}

<div class="manuscript-head"><div><h3>Accepted Book Structure</h3><p class="muted">Front matter, accepted story pages/spreads and end matter. These records feed the Illustration Studio.</p></div><div class="structure-actions"><button class="primary" onclick="editSpread()">+ Add Page / Spread</button></div></div>
<div class="panel"><div class="spread-list">${b.spreads.length?b.spreads.map((s,i)=>`<div class="spread" onclick="editSpread(${i})"><div><div class="spread-no">${esc(s.pages||("Item "+(i+1)))}</div><div class="type-badge">${esc(s.type||"Story Spread")}</div></div><div><b>${esc(s.title||"Untitled")}</b><div class="spread-text">${esc((s.text||"No text allocated yet.").slice(0,180))}</div></div><span class="status">${esc(s.status||"Draft")}</span></div>`).join(""):'<div class="empty"><h3>No accepted page plan yet</h3><p class="muted">Set up the book structure, create a proposed page plan, review it, then accept it.</p></div>'}</div></div>`}

function collectStoryForm(){return {title:current.title||"",bookType:current.type||"",series:current.series||"",premise:$("#storyPremise")?.value||current.story.premise,audience:$("#storyAudience")?.value||current.story.audience,wordTarget:$("#storyWords")?.value||current.story.wordTarget,tone:$("#storyTone")?.value||current.story.tone,manuscript:$("#storyManuscript")?.value||current.story.manuscript,notes:$("#storyNotes")?.value||current.story.notes,status:$("#storyStatus")?.value||current.story.status,structure:current.structure}}
function setAIResult(html,cls=""){let el=$("#aiResult");if(el)el.innerHTML=`<div class="ai-result ${cls}">${html}</div>`}
async function runTextAI(action){if(!aiConfigured()){setAIResult('<div class="warning">Enter and save the secure generation service URL first. The rest of the PWA will continue to work normally.</div>');return}setAIResult('<p class="muted">Generating…</p>');try{let data=await aiCall(action,collectStoryForm());if(action==="pagePlan"){if(!Array.isArray(data.plan))throw new Error("The service did not return a page plan.");current.pagePlanProposal=data.plan.map((x,i)=>({pages:x.pages||"",type:x.type||"Story Spread",title:x.title||`Scene ${i+1}`,text:x.text||"",scene:x.scene||"",illustration:x.illustration||"",notes:x.notes||"",status:"Draft"}));save();renderTab();return}let text=data.text||"";if(!text)throw new Error("The service returned no text.");let label=action==="developIdea"?"Developed idea":action==="generateDraft"?"Generated story draft":"Revised story";setAIResult(`<h4>${label}</h4><textarea id="aiGeneratedText">${esc(text)}</textarea><div class="ai-actions"><button class="secondary" onclick="clearAIResult()">Discard</button><button class="primary" onclick="applyAIText('${action}')">Apply to Story</button></div>`)}catch(e){setAIResult(`<div class="warning"><b>Generation unavailable:</b> ${esc(e.message)}<br>The local book project has not been changed.</div>`,"ai-error")}}
function clearAIResult(){setAIResult("")}
function applyAIText(action){let text=$("#aiGeneratedText")?.value||"";if(!text)return;if(action==="developIdea"){$("#storyPremise").value=text;current.story.premise=text}else{$("#storyManuscript").value=text;current.story.manuscript=text;if(action==="generateDraft"&&current.story.status==="Idea")current.story.status="Draft"}current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:action==="developIdea"?"AI-developed idea applied":action==="generateDraft"?"AI story draft applied":"AI story revision applied"});save();renderTab()}
function structureSummary(b){let s=b.structure||{},pc=Number(s.pageCount)||24,f=Number(s.frontPages)||0,e=Number(s.endPages)||0,story=Math.max(0,pc-f-e),units=s.mode==="pages"?story:Math.ceil(story/2);return `<span class="summary-chip"><b>${pc}</b> total pages</span><span class="summary-chip"><b>${f}</b> front matter</span><span class="summary-chip"><b>${story}</b> story pages</span><span class="summary-chip"><b>${e}</b> end matter</span><span class="summary-chip"><b>${units}</b> planned story ${s.mode==="pages"?"pages":"units"}</span>`}

function saveStructure(){let sel=$("#cfgPages").value,custom=Number($("#cfgCustom").value),pc=sel==="custom"?custom:Number(sel),front=Number($("#cfgFront").value),end=Number($("#cfgEnd").value);if(!pc||pc<8||pc%2!==0){alert("Enter an even total page count of at least 8.");return false}if(front+end>=pc){alert("Front and end matter must leave some pages for the story.");return false}current.structure={pageCount:pc,frontPages:front,endPages:end,mode:$("#cfgMode").value};save();renderTab();return true}

function sentenceChunks(text,count){let paras=text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);let parts=[];paras.forEach(p=>{let ss=p.match(/[^.!?]+[.!?]+(?:["'’”])?|[^.!?]+$/g)||[p];ss.forEach(x=>{x=x.trim();if(x)parts.push(x)})});if(!parts.length)return Array.from({length:count},()=>[]);let total=parts.reduce((n,x)=>n+x.split(/\s+/).length,0),target=Math.max(1,total/count),out=[],bucket=[],words=0;for(let i=0;i<parts.length;i++){let w=parts[i].split(/\s+/).length;if(out.length<count-1&&bucket.length&&words+w>target){out.push(bucket);bucket=[];words=0}bucket.push(parts[i]);words+=w}out.push(bucket);while(out.length<count)out.push([]);while(out.length>count){let last=out.pop();out[out.length-1]=out[out.length-1].concat(last)}return out}

function createPagePlan(){let manuscript=$("#storyManuscript")?$("#storyManuscript").value:current.story.manuscript;current.story.manuscript=manuscript;if($("#storyPremise")){current.story.premise=$("#storyPremise").value;current.story.audience=$("#storyAudience").value;current.story.wordTarget=$("#storyWords").value;current.story.tone=$("#storyTone").value;current.story.notes=$("#storyNotes").value;current.story.status=$("#storyStatus").value}
let sel=$("#cfgPages").value,pc=sel==="custom"?Number($("#cfgCustom").value):Number(sel),front=Number($("#cfgFront").value),end=Number($("#cfgEnd").value),mode=$("#cfgMode").value;if(!pc||pc<8||pc%2!==0||front+end>=pc){alert("Check the Book Structure Setup first.");return}current.structure={pageCount:pc,frontPages:front,endPages:end,mode};
let storyPages=pc-front-end,units=mode==="pages"?storyPages:Math.ceil(storyPages/2),chunks=sentenceChunks(manuscript,units),proposal=[],page=front+1;
for(let i=0;i<units;i++){let last=pc-end,endPage=mode==="pages"?page:Math.min(page+1,last);proposal.push({pages:endPage===page?String(page):`${page}–${endPage}`,type:mode==="pages"?"Story Page":"Story Spread",title:i===0?"Opening scene":i===units-1?"Closing scene":`Scene ${i+1}`,text:(chunks[i]||[]).join(" "),scene:"",illustration:"",notes:"",status:"Draft"});page=endPage+1}
current.pagePlanProposal=proposal;current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:`Proposed ${pc}-page book plan created (${units} story units)`});save();renderTab()}

function renderProposal(b){if(!b.pagePlanProposal||!b.pagePlanProposal.length)return "";return `<div class="panel proposal"><div class="proposal-head"><div><h3>Proposed Page Plan</h3><p class="muted">Review and edit this proposal. Nothing below replaces the accepted structure until you choose Accept Plan.</p></div><div><button class="secondary" onclick="discardProposal()">Discard</button> <button class="primary" onclick="acceptProposal()">Accept Plan</button></div></div>${!b.story.manuscript.trim()?'<div class="warning">There is no manuscript text yet, so the proposal contains empty story units ready for manual entry.</div>':""}<div class="proposal-list">${b.pagePlanProposal.map((x,i)=>`<div class="proposal-row"><div class="proposal-page">${esc(x.pages)}<div class="type-badge">${esc(x.type)}</div></div><div><input value="${attr(x.title)}" onchange="updateProposal(${i},'title',this.value)"><textarea onchange="updateProposal(${i},'text',this.value)">${esc(x.text)}</textarea></div></div>`).join("")}</div></div>`}
function updateProposal(i,k,v){current.pagePlanProposal[i][k]=v;save()}
function discardProposal(){if(confirm("Discard the proposed page plan?")){current.pagePlanProposal=[];save();renderTab()}}
function frontMatterRecords(){let f=Number(current.structure.frontPages)||0,a=[];for(let p=1;p<=f;p++){let type=p===1?"Half Title":p===2?"Copyright / Dedication":p===3?"Title Page":"Other",title=p===1?"Half title":p===2?"Copyright and dedication":p===3?"Full title page":`Front matter ${p}`;a.push({pages:String(p),type,title,text:"",scene:"",illustration:"",notes:"",status:"Draft"})}return a}
function endMatterRecords(){let pc=Number(current.structure.pageCount)||24,e=Number(current.structure.endPages)||0,a=[];for(let p=pc-e+1;p<=pc;p++)a.push({pages:String(p),type:"End Page",title:e===1?"End page":`End matter ${p}`,text:"",scene:"",illustration:"",notes:"",status:"Draft"});return a}
function acceptProposal(){if(current.spreads.length&&!confirm("Accepting this proposal will replace the current accepted book structure. Continue?"))return;current.spreads=[...frontMatterRecords(),...current.pagePlanProposal.map(x=>({...x})),...endMatterRecords()];current.pagePlanProposal=[];current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:"Proposed page plan accepted"});save();renderTab()}
function saveStory(){let s=current.story;s.premise=$("#storyPremise").value;s.audience=$("#storyAudience").value;s.wordTarget=$("#storyWords").value;s.tone=$("#storyTone").value;s.manuscript=$("#storyManuscript").value;s.notes=$("#storyNotes").value;s.status=$("#storyStatus").value;current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:`Story workspace saved (${s.status})`});save();renderTab()}
function editSpread(i){let s=i===undefined?{pages:"",type:"Story Spread",title:"",text:"",scene:"",illustration:"",notes:"",status:"Draft"}:{...current.spreads[i]};$("#tabContent").innerHTML=`<button class="link" onclick="renderTab()">← Back to manuscript</button><div class="panel editor"><h3>${i===undefined?"Add":"Edit"} Page / Spread</h3><div class="split"><label>Page(s) / spread<input id="spPages" value="${attr(s.pages)}" placeholder="e.g. 6–7"></label><label>Page type<select id="spType">${["Half Title","Copyright / Dedication","Title Page","Story Page","Story Spread","End Page","Other"].map(x=>`<option ${x===s.type?"selected":""}>${x}</option>`).join("")}</select></label></div><label>Short title<input id="spTitle" value="${attr(s.title)}"></label><label>Text allocated to this page/spread<textarea class="storytext" id="spText">${esc(s.text)}</textarea></label><div class="split"><label>Scene description<textarea id="spScene">${esc(s.scene)}</textarea></label><label>Illustration brief<textarea id="spIllustration">${esc(s.illustration)}</textarea></label></div><label>Notes<textarea id="spNotes">${esc(s.notes)}</textarea></label><label>Status<select id="spStatus">${["Draft","Review","Text Approved","Illustration Ready","Complete"].map(x=>`<option ${x===s.status?"selected":""}>${x}</option>`).join("")}</select></label><div class="actions">${i!==undefined?`<button class="danger" onclick="deleteSpread(${i})">Delete</button>`:""}<button class="secondary" onclick="renderTab()">Cancel</button><button class="primary" onclick="saveSpread(${i===undefined?"null":i})">Save</button></div></div>`}
function saveSpread(i){let s={pages:$("#spPages").value.trim(),type:$("#spType").value,title:$("#spTitle").value.trim(),text:$("#spText").value,scene:$("#spScene").value,illustration:$("#spIllustration").value,notes:$("#spNotes").value,status:$("#spStatus").value};if(i===null)current.spreads.push(s);else current.spreads[i]=s;current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:`${s.type} ${s.pages||"record"} ${i===null?"added":"updated"}`});save();renderTab()}
function deleteSpread(i){if(confirm("Delete this page/spread record?")){current.spreads.splice(i,1);save();renderTab()}}
function renderIllustrations(c,b){let il=b.illustration||{styleMaster:{},characters:[],environments:[]},rawStory=b.spreads.filter(x=>x.type==="Story Spread"||x.type==="Story Page"),seen=new Set(),story=rawStory.filter(x=>{let k=[x.pages,x.type,x.title].join("|");if(seen.has(k))return false;seen.add(k);return true});c.innerHTML=`<div class="manuscript-head"><div><h3>Illustration Studio</h3><p class="muted">Create consistent visual references, then manage artwork scene by scene.</p></div></div>
<div class="ill-grid">
<div class="panel"><h3>Style Master</h3><label>Style name<input id="styleName" value="${attr(il.styleMaster.name||"")}" placeholder="e.g. Cosy Bedtime Watercolour"></label><label>Visual style / consistency rules<textarea id="styleDesc">${esc(il.styleMaster.description||"")}</textarea></label><label>Notes<textarea id="styleNotes">${esc(il.styleMaster.notes||"")}</textarea></label><label>Status<select id="styleStatus">${["Not Started","Draft","Review","Approved"].map(x=>`<option ${x===(il.styleMaster.status||"Not Started")?"selected":""}>${x}</option>`).join("")}</select></label><div class="prompt-include">${il.styleMaster.status==="Approved"?"✓ Approved — included in generation briefs":"Approve this Style Master before using it for generation."}</div><button class="primary" onclick="saveStyleMaster()">Save Style Master</button></div>
<div class="panel"><h3>Reference Library</h3><p class="muted">Character and environment masters provide the consistency references for every scene. Only Approved masters are included in generation briefs.</p><div class="reference-summary"><span><b>${il.characters.length}</b> characters</span><span><b>${il.environments.length}</b> environments</span><span><b>${[...il.characters,...il.environments].filter(x=>x.status==="Approved").length}</b> approved</span></div><div class="structure-actions"><button class="secondary" onclick="addAsset('character')">+ Character</button><button class="secondary" onclick="addAsset('environment')">+ Environment</button></div><div class="asset-list">${[...il.characters.map((x,i)=>assetCard(x,"character",i)),...il.environments.map((x,i)=>assetCard(x,"environment",i))].join("")||'<p class="muted">No reference masters yet.</p>'}</div></div>
</div>
<div class="manuscript-head"><div><h3>Scene Artwork</h3><p class="muted">${story.length} accepted story scene${story.length===1?"":"s"}. Illustration briefs stay linked to the manuscript records.</p></div></div>
${story.length?story.map(s=>sceneCard(s,b.spreads.indexOf(s))).join(""):'<div class="panel empty"><h3>No accepted story scenes yet</h3><p class="muted">Accept a page plan in Manuscript first. The Illustration Studio will then use those scene records.</p></div>'}`}

function assetCard(x,type,i){let st=x.status||"Draft",cls=st==="Approved"?"master-approved":st==="Review"?"master-review":"";return `<div class="asset-card"><span class="master-status ${cls}">${esc(st)}</span><h4>${esc(x.name||("Untitled "+type))}</h4><p>${esc((x.description||"").slice(0,150))}</p><div class="prompt-include">${st==="Approved"?"✓ Included in generation briefs":"Not yet included in generation briefs"}</div><button class="link" onclick="addAsset('${type}',${i})">Edit</button></div>`}

function addAsset(type,i){let arr=type==="character"?current.illustration.characters:current.illustration.environments,x=i===undefined?{name:"",description:"",reference:"",notes:"",status:"Draft"}:{...arr[i]};$("#tabContent").innerHTML=`<button class="link" onclick="renderTab()">← Back to Illustration Studio</button><div class="panel asset-form"><h3>${i===undefined?"Add":"Edit"} ${type==="character"?"Character Master":"Environment Master"}</h3><label>Name<input id="assetName" value="${attr(x.name)}"></label><label>Master description<textarea id="assetDesc">${esc(x.description)}</textarea></label><label>Reference image / file note<input id="assetRef" value="${attr(x.reference)}" placeholder="e.g. Little Fox clean character sheet"></label><div class="refbox">Image upload/storage will be added with the generation backend. For now this records the reference asset name so the project structure is ready.</div><label>Consistency notes<textarea id="assetNotes">${esc(x.notes)}</textarea></label><label>Status<select id="assetStatus">${["Draft","Review","Approved"].map(v=>`<option ${v===x.status?"selected":""}>${v}</option>`).join("")}</select></label><div class="actions">${i!==undefined?`<button class="danger" onclick="deleteAsset('${type}',${i})">Delete</button>`:""}<button class="secondary" onclick="renderTab()">Cancel</button><button class="primary" onclick="saveAsset('${type}',${i===undefined?"null":i})">Save</button></div></div>`}

function saveAsset(type,i){let x={name:$("#assetName").value.trim(),description:$("#assetDesc").value,reference:$("#assetRef").value,notes:$("#assetNotes").value,status:$("#assetStatus").value},arr=type==="character"?current.illustration.characters:current.illustration.environments;if(i===null)arr.push(x);else arr[i]=x;current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:`${type==="character"?"Character":"Environment"} master ${x.name||"updated"} saved`});save();renderTab()}
function deleteAsset(type,i){if(confirm("Delete this reference master?")){let arr=type==="character"?current.illustration.characters:current.illustration.environments;arr.splice(i,1);save();renderTab()}}
function saveStyleMaster(){current.illustration.styleMaster={name:$("#styleName").value.trim(),description:$("#styleDesc").value,notes:$("#styleNotes").value,status:$("#styleStatus").value};current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:"Style Master saved"});save();renderTab()}
function sceneCard(s,i){return `<div class="scene-card"><div class="scene-top"><div><div class="spread-no">${esc(s.pages)}</div><div class="type-badge">${esc(s.type)}</div></div><div><h3>${esc(s.title||"Untitled scene")}</h3><p>${esc(s.text||"No story text allocated.")}</p></div><select class="ill-status" onchange="updateSceneArt(${i},'illustrationStatus',this.value)">${["Not Started","Brief Ready","Generating","Review","Approved"].map(x=>`<option ${x===(s.illustrationStatus||"Not Started")?"selected":""}>${x}</option>`).join("")}</select></div><div class="scene-body"><label>Scene description<textarea onchange="updateSceneArt(${i},'scene',this.value)">${esc(s.scene||"")}</textarea></label><label>Illustration brief<textarea onchange="updateSceneArt(${i},'illustration',this.value)">${esc(s.illustration||"")}</textarea></label></div><div class="scene-body"><label>Generated / final image reference<input value="${attr(s.imageRef||"")}" onchange="updateSceneArt(${i},'imageRef',this.value)" placeholder="Image storage will be connected later"></label><label>Image review notes<input value="${attr(s.imageNotes||"")}" onchange="updateSceneArt(${i},'imageNotes',this.value)"></label></div><div class="scene-actions"><button class="secondary" onclick="copyBrief(${i})">Copy Generation Brief</button><button class="primary" disabled title="Enabled when image generation backend is connected">Generate Image</button></div></div>`}
function updateSceneArt(i,k,v){current.spreads[i][k]=v;save()}
function copyBrief(i){let s=current.spreads[i],il=current.illustration,chars=il.characters.filter(x=>x.status==="Approved").map(x=>`${x.name}: ${x.description}`).join("\n"),envs=il.environments.filter(x=>x.status==="Approved").map(x=>`${x.name}: ${x.description}`).join("\n"),txt=`STYLE MASTER\n${il.styleMaster.description||"(not defined)"}\n\nAPPROVED CHARACTERS\n${chars||"(none)"}\n\nAPPROVED ENVIRONMENTS\n${envs||"(none)"}\n\nSCENE ${s.pages} — ${s.title||""}\nStory text: ${s.text||""}\nScene description: ${s.scene||""}\nIllustration brief: ${s.illustration||""}`;navigator.clipboard.writeText(txt).then(()=>alert("Generation brief copied to clipboard.")).catch(()=>prompt("Copy this generation brief:",txt))}
function setStatus(stage,i,v){current.workflow[stage][i].status=v;save();renderTab()}
function addLog(e){e.preventDefault();let v=$("#logText").value.trim();if(v){current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:v});save();renderTab()}}
function exportBackup(){let blob=new Blob([JSON.stringify({app:"Book Creation Studio",version:"0.6",exported:new Date().toISOString(),data},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`book-creation-studio-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importBackup(file){let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result),d=x.data||x;if(!Array.isArray(d.books))throw Error();if(!confirm(`Restore ${d.books.length} project(s)? This replaces the data stored in this browser.`))return;data=d;data.books.forEach(ensureBook);save();renderBooks();alert("Backup restored.")}catch(e){alert("Not a valid Book Creation Studio backup.")}};r.readAsText(file)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function attr(s){return esc(s).replace(/`/g,"&#96;")}
$("#exportBtn").onclick=exportBackup;$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=""};$("#newBook").onclick=openNew;$("#cancel").onclick=()=>$("#bookDialog").close();$("#back").onclick=()=>{$("#workspace").classList.add("hidden");$("#dashboard").classList.remove("hidden");renderBooks()};
$("#bookForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),b={id:Date.now().toString(36),title:f.get("title"),type:f.get("type"),series:f.get("series"),author:f.get("author"),imprint:f.get("imprint"),trim:f.get("trim"),interior:f.get("interior"),formats:f.get("formats"),workflow:makeWorkflow(f.get("type")),story:{premise:"",audience:"5–7",wordTarget:"",tone:"Gentle, cosy and reassuring",manuscript:"",notes:"",status:"Idea"},structure:{pageCount:24,frontPages:3,endPages:1,mode:"spreads"},pagePlanProposal:[],illustration:{styleMaster:{name:"",description:"",notes:"",status:"Not Started"},characters:[],environments:[]},spreads:[],log:[{date:new Date().toLocaleDateString("en-GB"),text:"Project created"}]};data.books.unshift(b);save();$("#bookDialog").close();e.target.reset();renderBooks();openBook(b.id)};
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
save();renderBooks();