const KEY="bookCreationStudio.v01";
const tabs=["Overview","Manuscript","Illustrations","Production","Publishing","Project Log"];
const workflows={"Children's Picture Book":{"Manuscript":["Define concept and audience","Develop story outline","Draft manuscript","Review and revise manuscript","Lock manuscript","Break manuscript into pages / spreads"],"Illustrations":["Approve Character Master","Approve Environment Master","Approve Style Master","Create Illustration Schedule","Generate / source scene images","Review scene sequence","Approve final illustrations"],"Production":["Confirm trim size, bleed and margins","Set up Affinity document","Place final text and images","Preflight image resolution and layout","Export print-ready interior PDF","Create and check cover"],"Publishing":["Prepare title, subtitle and description","Prepare keywords and categories","Set pricing and territories","Upload manuscript and cover to KDP","Run KDP preview","Order / review proof","Publish","Prepare A+ Content"]},"Illustrated Non-Fiction":{"Manuscript":["Define concept and reader","Create chapter structure","Research and draft entries","Fact-check sources and claims","Edit and proofread","Lock manuscript"],"Illustrations":["Define illustration style","Create illustration list","Produce / source artwork","Review and approve artwork"],"Production":["Confirm trim and interior specification","Build Affinity document","Place text and artwork","Preflight","Export print-ready PDF","Create cover"],"Publishing":["Prepare KDP metadata","Keywords and categories","Pricing","Upload and preview","Proof","Publish","A+ Content"]}};
const generic={"Manuscript":["Define concept and audience","Create structure","Draft content","Review and edit","Proofread","Lock manuscript"],"Illustrations":["Decide whether artwork is required","Create artwork list","Produce / source artwork","Approve final artwork"],"Production":["Confirm book specification","Compile interior","Preflight","Export final files","Create cover"],"Publishing":["Prepare metadata","Keywords and categories","Pricing","Upload and preview","Proof","Publish"]};
let data=JSON.parse(localStorage.getItem(KEY)||'{"books":[]}'),current=null,active="Overview";
const $=s=>document.querySelector(s);
function ensureBook(b){if(!b.spreads)b.spreads=[];if(!b.log)b.log=[];if(!b.story)b.story={premise:"",audience:"5–7",wordTarget:"",tone:"Gentle, cosy and reassuring",manuscript:"",notes:"",status:"Idea"};return b}
data.books.forEach(ensureBook);
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function makeWorkflow(type){let src=workflows[type]||generic,o={};for(const [stage,items] of Object.entries(src))o[stage]=items.map(name=>({name,status:"Not Started"}));return o}
function pct(b){let a=Object.values(b.workflow).flat(),n=a.filter(x=>x.status==="Complete").length;return a.length?Math.round(n/a.length*100):0}
function renderBooks(){let box=$("#books");if(!data.books.length){box.innerHTML='<div class="panel empty"><h3>No book projects yet</h3><p class="muted">Create your first project to generate its workflow.</p><button class="primary" onclick="openNew()">Create First Book</button></div>';return}box.innerHTML=data.books.map(b=>`<article class="card" onclick="openBook('${b.id}')"><span class="badge">${esc(b.type)}</span><h3>${esc(b.title)}</h3><p class="muted">${esc(b.series||"Standalone")} · ${esc(b.formats)}</p><div class="progress"><span style="width:${pct(b)}%"></span></div><strong>${pct(b)}% complete</strong><p class="small muted">${b.spreads.length} page/spread records · Story: ${esc(b.story.status)}</p></article>`).join("")}
function openNew(){$("#bookDialog").showModal()}
function openBook(id){current=ensureBook(data.books.find(b=>b.id===id));active="Overview";$("#dashboard").classList.add("hidden");$("#workspace").classList.remove("hidden");renderWorkspace()}
function renderWorkspace(){let b=current;$("#bookHeader").innerHTML=`<h2>${esc(b.title)}</h2><p class="muted">${esc(b.type)} · ${esc(b.author)} · ${esc(b.imprint)}</p>`;$("#tabs").innerHTML=tabs.map(t=>`<button class="${t===active?"active":""}" onclick="showTab('${t}')">${t}</button>`).join("");renderTab()}
function showTab(t){active=t;renderWorkspace()}
function renderTab(){let b=current,c=$("#tabContent");
if(active==="Overview"){c.innerHTML=`<div class="grid"><div class="panel"><h3>Project</h3><p><b>Series:</b> ${esc(b.series||"—")}</p><p><b>Trim:</b> ${esc(b.trim||"—")}</p><p><b>Interior:</b> ${esc(b.interior)}</p><p><b>Formats:</b> ${esc(b.formats)}</p></div><div class="panel"><h3>Progress</h3><div class="progress"><span style="width:${pct(b)}%"></span></div><h2>${pct(b)}%</h2><p class="muted">Based on completed workflow tasks.</p></div></div><div class="note"><b>Creation flow:</b> develop the story → approve manuscript → create page plan → prepare illustration briefs → generate/review artwork → production and publishing.</div>`;return}
if(active==="Manuscript"){renderManuscript(c,b);return}
if(active==="Project Log"){c.innerHTML=`<div class="panel"><h3>Project Log</h3>${b.log.map(x=>`<p><b>${x.date}</b> — ${esc(x.text)}</p>`).join("")||"<p class=muted>No entries yet.</p>"}<form onsubmit="addLog(event)"><input id="logText" placeholder="Add a decision, change or milestone…" required><button class="primary">Add Entry</button></form></div>`;return}
let tasks=b.workflow[active]||[];c.innerHTML=`<div class="panel"><h3>${active}</h3>${tasks.map((x,i)=>`<div class="task"><span>${esc(x.name)}</span><select onchange="setStatus('${active}',${i},this.value)">${["Not Started","In Progress","Review","Complete"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></div>`).join("")}</div>`}
function renderManuscript(c,b){let st=b.story;c.innerHTML=`<div class="manuscript-head"><div><h3>Story Workspace</h3><p class="muted">Develop and approve the whole story before breaking it into the book's page structure.</p></div><button class="primary" onclick="saveStory()">Save Story</button></div>
<div class="stagebar">${["Idea","Outline","Draft","Review","Approved"].map(x=>`<span class="stagepill ${x===st.status?"on":""}">${x}</span>`).join("")}</div>
<div class="story-grid"><div class="panel story-editor"><label>Working / final manuscript<textarea id="storyManuscript" placeholder="Write or paste the complete story here…">${esc(st.manuscript)}</textarea></label><label>Story notes<textarea id="storyNotes">${esc(st.notes)}</textarea></label></div>
<div class="panel"><h3>Story Brief</h3><label>Premise / idea<textarea id="storyPremise">${esc(st.premise)}</textarea></label><label>Target audience<input id="storyAudience" value="${esc(st.audience)}"></label><label>Target word count<input id="storyWords" value="${esc(st.wordTarget)}" placeholder="e.g. 650"></label><label>Tone / style<textarea id="storyTone">${esc(st.tone)}</textarea></label><label>Development status<select id="storyStatus">${["Idea","Outline","Draft","Review","Approved"].map(x=>`<option ${x===st.status?"selected":""}>${x}</option>`).join("")}</select></label></div></div>
<div class="manuscript-head"><div><h3>Book Structure</h3><p class="muted">Front matter, story pages/spreads and end matter. These records feed the Illustration Studio.</p></div><div class="structure-actions"><button class="secondary" onclick="starterStructure()">Create Picture Book Structure</button><button class="primary" onclick="editSpread()">+ Add Page / Spread</button></div></div>
<div class="panel"><div class="spread-list">${b.spreads.length?b.spreads.map((s,i)=>`<div class="spread" onclick="editSpread(${i})"><div><div class="spread-no">${esc(s.pages||("Item "+(i+1)))}</div><div class="type-badge">${esc(s.type||"Story Spread")}</div></div><div><b>${esc(s.title||"Untitled")}</b><div class="spread-text">${esc((s.text||"No text allocated yet.").slice(0,180))}</div></div><span class="status">${esc(s.status||"Draft")}</span></div>`).join(""):'<div class="empty"><h3>No book structure yet</h3><p class="muted">For a picture book, create the starter structure or add records manually.</p></div>'}</div></div>`}
function saveStory(){let s=current.story;s.premise=$("#storyPremise").value;s.audience=$("#storyAudience").value;s.wordTarget=$("#storyWords").value;s.tone=$("#storyTone").value;s.manuscript=$("#storyManuscript").value;s.notes=$("#storyNotes").value;s.status=$("#storyStatus").value;current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:`Story workspace saved (${s.status})`});save();renderTab()}
function starterStructure(){if(current.spreads.length&&!confirm("This will add a standard picture-book starter structure to the existing records. Continue?"))return;let starter=[["1","Half Title","Half title",""],["2","Copyright / Dedication","Copyright and dedication",""],["3","Title Page","Full title page",""],["4–5","Story Spread","Opening scene",""],["6–7","Story Spread","Scene 2",""],["8–9","Story Spread","Scene 3",""],["10–11","Story Spread","Scene 4",""],["12–13","Story Spread","Scene 5",""],["14–15","Story Spread","Scene 6",""],["16–17","Story Spread","Scene 7",""],["18–19","Story Spread","Scene 8",""],["20–21","Story Spread","Scene 9",""],["22–23","Story Spread","Closing scene",""],["24","End Page","End page",""]];starter.forEach(x=>current.spreads.push({pages:x[0],type:x[1],title:x[2],text:x[3],scene:"",illustration:"",notes:"",status:"Draft"}));current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:"24-page picture-book starter structure created"});save();renderTab()}
function editSpread(i){let s=i===undefined?{pages:"",type:"Story Spread",title:"",text:"",scene:"",illustration:"",notes:"",status:"Draft"}:{...current.spreads[i]};$("#tabContent").innerHTML=`<button class="link" onclick="renderTab()">← Back to manuscript</button><div class="panel editor"><h3>${i===undefined?"Add":"Edit"} Page / Spread</h3><div class="split"><label>Page(s) / spread<input id="spPages" value="${attr(s.pages)}" placeholder="e.g. 6–7"></label><label>Page type<select id="spType">${["Half Title","Copyright / Dedication","Title Page","Story Page","Story Spread","End Page","Other"].map(x=>`<option ${x===s.type?"selected":""}>${x}</option>`).join("")}</select></label></div><label>Short title<input id="spTitle" value="${attr(s.title)}"></label><label>Text allocated to this page/spread<textarea class="storytext" id="spText">${esc(s.text)}</textarea></label><div class="split"><label>Scene description<textarea id="spScene">${esc(s.scene)}</textarea></label><label>Illustration brief<textarea id="spIllustration">${esc(s.illustration)}</textarea></label></div><label>Notes<textarea id="spNotes">${esc(s.notes)}</textarea></label><label>Status<select id="spStatus">${["Draft","Review","Text Approved","Illustration Ready","Complete"].map(x=>`<option ${x===s.status?"selected":""}>${x}</option>`).join("")}</select></label><div class="actions">${i!==undefined?`<button class="danger" onclick="deleteSpread(${i})">Delete</button>`:""}<button class="secondary" onclick="renderTab()">Cancel</button><button class="primary" onclick="saveSpread(${i===undefined?"null":i})">Save</button></div></div>`}
function saveSpread(i){let s={pages:$("#spPages").value.trim(),type:$("#spType").value,title:$("#spTitle").value.trim(),text:$("#spText").value,scene:$("#spScene").value,illustration:$("#spIllustration").value,notes:$("#spNotes").value,status:$("#spStatus").value};if(i===null)current.spreads.push(s);else current.spreads[i]=s;current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:`${s.type} ${s.pages||"record"} ${i===null?"added":"updated"}`});save();renderTab()}
function deleteSpread(i){if(confirm("Delete this page/spread record?")){current.spreads.splice(i,1);save();renderTab()}}
function setStatus(stage,i,v){current.workflow[stage][i].status=v;save();renderTab()}
function addLog(e){e.preventDefault();let v=$("#logText").value.trim();if(v){current.log.unshift({date:new Date().toLocaleDateString("en-GB"),text:v});save();renderTab()}}
function exportBackup(){let blob=new Blob([JSON.stringify({app:"Book Creation Studio",version:"0.3",exported:new Date().toISOString(),data},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`book-creation-studio-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importBackup(file){let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result),d=x.data||x;if(!Array.isArray(d.books))throw Error();if(!confirm(`Restore ${d.books.length} project(s)? This replaces the data stored in this browser.`))return;data=d;data.books.forEach(ensureBook);save();renderBooks();alert("Backup restored.")}catch(e){alert("Not a valid Book Creation Studio backup.")}};r.readAsText(file)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function attr(s){return esc(s).replace(/`/g,"&#96;")}
$("#exportBtn").onclick=exportBackup;$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=""};$("#newBook").onclick=openNew;$("#cancel").onclick=()=>$("#bookDialog").close();$("#back").onclick=()=>{$("#workspace").classList.add("hidden");$("#dashboard").classList.remove("hidden");renderBooks()};
$("#bookForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),b={id:Date.now().toString(36),title:f.get("title"),type:f.get("type"),series:f.get("series"),author:f.get("author"),imprint:f.get("imprint"),trim:f.get("trim"),interior:f.get("interior"),formats:f.get("formats"),workflow:makeWorkflow(f.get("type")),story:{premise:"",audience:"5–7",wordTarget:"",tone:"Gentle, cosy and reassuring",manuscript:"",notes:"",status:"Idea"},spreads:[],log:[{date:new Date().toLocaleDateString("en-GB"),text:"Project created"}]};data.books.unshift(b);save();$("#bookDialog").close();e.target.reset();renderBooks();openBook(b.id)};
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
save();renderBooks();